### ISSUE TITLE
Change Legend Position

### ISSUE THREAD

**Issue by JoKPro** [plger/sechm#2]
Hello,

Is there a way to specify the legend's position in the sechm function?

Thanks!

**Comment by plger** [comment]
Much of what works in `ComplexHeatmap` works with `sechm`. This means that you can for instance do this:
```
draw(sechm( ... ), heatmap_legend_side="bottom")
```
For more information about the draw parameters see:
```
?ComplexHeatmap::`draw,HeatmapList-method`
```
Alternatively, if you need more control, you can also disable the legend, build your own, and add it to the heatmap. Check the [ComplexHeatmap reference](https://jokergoo.github.io/ComplexHeatmap-reference/book/) for more info.

**Comment by JoKPro** [comment]
Yes that works,

thanks for the fast reply!
